Feature/footer
KateDietkova/wow-ice-cream pull request #4
Opened 2022-09-02 16:01 UTC by Stranger1978

2022-09-03 09:44 UTC, KateDietkova requested changes

2022-09-03 09:44 UTC, KateDietkova commented on src/partials/footer.html
> +        <div class="footer-social">
Зайвий div.footer-social

2022-09-03 09:44 UTC, KateDietkova commented on src/partials/footer.html
> +            <p class="footer-content__litle">homemade ice cream made
little та big це описові назви  що використовуються у модифікаторах, якщо потрібно  на якийсь тег додати ще другий клас) Через нижнє підкреслювання записуються елементи блоку, що позначають, що саме це за елемент) Виправ, будь-ласка, наприклад на клас - footer-content__text (для кожного p), якому можеш задати загальні стилі для обох p та  кожному p можеш додати ще окремі класи-модифікатори - footer-content__text--little та footer-content__text--big відповідно)

2022-09-03 09:44 UTC, KateDietkova commented on src/partials/footer.html
> +<div class="footer-bottom">
Краще задати клас footer-copyright)

2022-09-03 09:44 UTC, KateDietkova commented on src/partials/footer.html
> +        <span class="footer-contacts__text">Feel free to contact</span>
Не треба це обгортати в span, це можна обгорнути в `<p class="footer-contacts__text">Feel free to contact  <a href="tel:+610383766284" class="footer-contacts__tel">+61 (0) 383 766 284</a> </p>` . І тоді div.footer-contacts взагалі не потрібен

2022-09-03 09:44 UTC, KateDietkova commented on src/partials/footer.html
> +    </div>
div з класом контейнер має обгортати весь контент футера (окрім самого нижнього div де потрібна горизонтальна смуга)

2022-09-03 10:33 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +        color: var(--secondary-darktext-color);
Після того як підтягнеш зміни з мейну, виправ, будь ласка, значення color, замість --secondary-darktext-color (бо такої змінної вже нема) встав --primary-darktext-color)

2022-09-03 11:01 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +    &__big {
Модифікатори пишемо окремим правилом, не вкладаючи в інше) А от ховери, фокуси, псевдоелементи, псевдокласи вкладаємо) Зроби, будь ласка, окремим правилом footer-content__text--little і footer-content__text--little, а їх загальні стилі додай до правила .footer-content__text)

2022-09-03 20:01 UTC, Stranger1978 commented on src/partials/footer.html
> +<div class="footer-bottom">
Зроблено. Дякую

2022-09-03 20:01 UTC, Stranger1978 commented on src/partials/footer.html
> +            <p class="footer-content__litle">homemade ice cream made
Зроблено. Дякую

2022-09-03 20:05 UTC, Stranger1978 commented on src/partials/footer.html
> +        <div class="footer-social">
переймінував цей div у footer-links, обгорнув у нього соцмережі та телефон. це потрібно для подальшого позіціонування для планшету та десктопу, коли необхідно буде розташувати текст та посилання на соцмережі та телефон горизонтально.

2022-09-03 20:07 UTC, Stranger1978 commented on src/partials/footer.html
> +    </div>
Зроблено. перемістив закриваючий тег нижче до горізонтальної смуги ще вранку )). Дякую.

2022-09-03 20:08 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +        color: var(--secondary-darktext-color);
Зроблено. Дякую

2022-09-03 20:08 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +    &__big {
Зроблено. Дякую

2022-09-04 00:59 UTC, Stranger1978 commented on src/partials/footer.html
> +        <span class="footer-contacts__text">Feel free to contact</span>
span змінив на р, але дів не став чепати на той випадок якщо ще щось дадасться до макету в блоці контактів. завтра можу прибрати дів та подивитися на те як все буде працювати без нього

2022-09-04 08:30 UTC, KateDietkova commented on src/partials/footer.html
> +            </ul>
Тут здається `</ul>` стоїть прямо під лішкою `</li>` вирівняй, будь ласка)

2022-09-04 08:36 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +    &__text {
Елементи блоку також окремим правилом треба зробити, тобто окремо написати  `.footer-content__text`)

2022-09-04 08:39 UTC, KateDietkova commented on src/partials/footer.html
> +        <div class="footer-links">
Спробуй все ж таки без `<div class="footer-links">` бо ul веде себе точно так само як і дів, тобто це блоковий елемент і їй можна і без діва поставити з правої сторони)

2022-09-04 08:51 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +        justify-content: end;
`justify-content: end;` можна прибрати, щоб соцмережі та текст притиснулись до правої сторони, треба просто лівому діву .footer-content задати правий марджин (текст і так буде на всю ширину діва в такому випадку і буде притиснутий до правої сторони, а списку соц мереж ти вже і так задав justify-content: flex-end; вони також залишаться справа)

2022-09-04 08:53 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +    text-align: right;
Не потрібно  text-align: right;, оскільки коли ти задаш як я написала вище властивості  .footer-content правий марджин, він притиснеться до правої сторони)

2022-09-04 08:55 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
>      &__text {
Так само, елементи пишемо окремим правилом) Винеси,, будь ласка .footer-contacts__text окремо і так само .footer-contacts__tel)

2022-09-04 09:05 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +        width: 1167px;
Ширину не потрібно задавати до .footer-copyright)

2022-09-04 09:09 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +
Сюди спробуй ще додати row-gap: 30px; і прибрати цей селектор сусіда, що нижче написаний) `.social-network__item + .social-network__item {
    margin-left: 30px;
}`

2022-09-04 09:18 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +    border-radius: 50%;
Сюди ще додай властивості     
    `display: flex;
    justify-content: center;
    align-items: center;
    width: 34px;
    height: 34px;`

2022-09-04 09:20 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +    fill: var(--primary-background-color);
І ще додай `transition: color 250ms cubic-bezier(0.4, 0, 0.2, 1), background-color 250ms cubic-bezier(0.4, 0, 0.2, 1);`

2022-09-04 09:27 UTC, KateDietkova commented on src/partials/footer.html
> +        <div class="footer-social">
Ок)

2022-09-04 10:00 UTC, Stranger1978 commented on src/partials/footer.html
> +            </ul>
якщо я вірно зрозумів, то я на один таб подвинув усі <li>

2022-09-04 10:16 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +    &__text {
Виправив. Дякую

2022-09-04 10:59 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +    text-align: right;
text-align: right; переніс до медіа-правила до планшетної версії. Марджин не потрібен тому що починаючи з 768рх застосовується до лівого та правого дивів спейс-бітвін

2022-09-04 11:00 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +        justify-content: end;
треба залишати, це для притискання до низу

2022-09-04 11:02 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
>      &__text {
Зробив. Дякую

2022-09-04 11:20 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +
row-gap: 30px не працює, але методом гугла та наукового тику досвідним шляхом було встановлено що в даному випадку працюють таки варіанти: column-gap: 30px; або gap: 0 30px; обрав перший варіант )

2022-09-04 11:27 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +        width: 1167px;
ширина потрібна, тому що на десктопній версії смуга не є безперервною.. там з'являються відступи зліва та справа.. довжина смуги 1167рх. Тому і поставив довжину, щоб після досягення 1200рх смуга була довжиною 1167рх та залишалась всередині екрану.. всі інші варіанти робили так що уся сторинка була всередині екрану, а смуга та копірайн залишались зліва

2022-09-04 11:29 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +    fill: var(--primary-background-color);
Зробив. Дякую

2022-09-04 12:44 UTC, Stranger1978 commented on src/sass/layouts/_footer.scss
> +    border-radius: 50%;
зробив, дякую. все стало круглим.. але розмір мені не зовсів сподобається.. буду зі спрайтом гратись.. закачаю  з нового макету знову усі іконки та спробую замінити.

2022-09-05 06:37 UTC, KateDietkova requested changes

2022-09-05 06:37 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +        width: 1167px;
Тоді краще постав, будь ласка, 1170px (враховуючи падінги контейнера, бо та довжина що вказана це трошки баг на макеті)

2022-09-05 06:37 UTC, KateDietkova commented on src/sass/layouts/_footer.scss
> +
Чудово)

2022-09-05 16:42 UTC, KateDietkova approved these changes

2022-09-05 16:42 UTC, merged