Feature/advantages
KateDietkova/wow-ice-cream pull request #7
Opened 2022-09-03 10:49 UTC by teyla12

2022-09-03 11:04 UTC, KateDietkova commented on src/partials/advantages.html
> +        <h3 class="advantages-uppertitle advantages-uppertitle-1">721</h3>
Числа це не заголовки, зроби, будь ласка, замість h3 - p)

2022-09-03 11:06 UTC, KateDietkova commented on src/partials/advantages.html
> +        <span class="advantages-icon"></span>
У тех завданні написано, що треба ці іконки поставити через псевдо елементи) Прибери, будь ласка `<span class="advantages-icon"></span>` та у стилях до лішок створи псевдоелемент через before)

2022-09-03 11:10 UTC, teyla12 commented on src/partials/advantages.html
> +        <h3 class="advantages-uppertitle advantages-uppertitle-1">721</h3>
добре, як думаєш клас також переназвати? З `advantages-uppertitle` на `advantages-number` наприклад.. Хоча там де кг. там не номер

2022-09-03 11:18 UTC, KateDietkova commented on src/sass/layouts/_advantages.scss
> +.advatages {
Через директиву  @extend зроби наслідування загального класу section (для нього стилі вже прописані) і задай padding-top: 0) Display flex для секції прибери, бо  весь контент огортає дів з класом контейнер, задай йому у розмітці додатковий клас наприклад advantages__container і вже на нього повісь флекс )

2022-09-03 11:24 UTC, teyla12 commented on src/partials/advantages.html
> +        <span class="advantages-icon"></span>
зробила

2022-09-03 11:35 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +.advatages {
При доданні стилів секції через @extend вибиває помилку, може треба оновити мейн

2022-09-03 11:44 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +.advatages {
зробила, але стилей для секції так і не бачу тому поставила `@extend %section !optional;`

2022-09-03 12:03 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +.advatages {
зробила

2022-09-03 12:22 UTC, KateDietkova requested changes

2022-09-03 12:22 UTC, KateDietkova commented on src/sass/layouts/_advantages.scss
> +  font-style: normal;
Якщо font-style: normal, його не потрібно прописувати, він наслідується)

2022-09-03 12:22 UTC, KateDietkova commented on src/sass/layouts/_advantages.scss
> +.advatages {
Стилі секції прописані не через плейсхолдер, треба наслідувати від класу, тобто так @extend .section )

2022-09-03 12:22 UTC, KateDietkova commented on src/sass/layouts/_advantages.scss
> +  display: block;
1. display: block - зайве, бо p і так блоковий елемент) 2.  justify-content: center; - не потрібен, оскільки це не флекс контейнер, властивістю  text-align: center; ти і так центруєш) 3.  line-height: 170%; прописувати як коефіцієнт, тобто так  line-height: 1.7; )

2022-09-03 12:22 UTC, KateDietkova commented on src/sass/layouts/_advantages.scss
> +  margin-right: auto;
margin-right: auto; і margin-left: auto; можеш прибрати) І так повинно центруватись, оскільки ти задаєш text-align: center; )

2022-09-03 12:22 UTC, KateDietkova commented on src/partials/advantages.html
> +      <li class="advantages-item">
Домовилися що будемо називати за методологією BEM, тобто в нас є наприклад блок`<ul class="advantages-list">` отже клас у лішок буде наприклад такий advantages-list__item, у p можна написати клас відштовхуючись від блокового елементу, тобто advantages-list__text, а коли хочеш додати ще один клас до одного й того ж елемента, то пишеш клас модифікатор, наприклад не advantages-uppertitle-1, а advantages-list__text--uppertitle )

2022-09-03 12:22 UTC, KateDietkova commented on src/sass/layouts/_advantages.scss
> +.advantages-uppertitle::before {
Всі псевдокласи, псевдоелементи, ховери та фокуси, вкладаємо у відповідне правило якого це стосується, наприклад `.advantages-list__text--uppertitle {
пишеш загальні стилі

/*І у цьому ж правилі прописуєш before*/
        &::before {
         }
}`

2022-09-03 12:22 UTC, KateDietkova commented on src/sass/layouts/_advantages.scss
> +    margin-bottom: 0;
Щоб не дублювати стилі перенеси margin-bottom: 28px; у медіазапит  @media screen and (max-width: 767px), а в інших медіазапитах прибери margin-bottom: 0;

2022-09-03 16:00 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +  font-style: normal;
зробила, так, це випадково

2022-09-03 16:05 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +  display: block;
зробила

2022-09-03 16:05 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +  margin-right: auto;
зробила

2022-09-03 16:12 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +  margin-right: auto;
зробила

2022-09-03 18:07 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +.advantages-uppertitle::before {
зробила

2022-09-03 18:11 UTC, teyla12 commented on src/partials/advantages.html
> +        <h3 class="advantages-uppertitle advantages-uppertitle-1">721</h3>
розібралась, зробила

2022-09-03 18:12 UTC, teyla12 commented on src/partials/advantages.html
> +      <li class="advantages-item">
зробила

2022-09-03 18:12 UTC, teyla12 commented on src/sass/layouts/_advantages.scss
> +    margin-bottom: 0;
зробила

2022-09-05 16:46 UTC, KateDietkova approved these changes

2022-09-05 16:46 UTC, merged